name: fire_flag
description: App wide feature flag manager utilizing the power of Firebase Remote Config.
version: 1.1.1
homepage: https://github.com/mastersam07/fire-flag

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_remote_config: ^0.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
